[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "cd backend",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m pip list | grep -i apscheduler || echo 'APScheduler not installed!'"
]

[variables]
PYTHONPATH = "/app"

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"
